include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_typing_uninitialized_variables: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    avoid_print: false

analyzer:
  errors:
    # 이 부분에서 원하는 경고를 비활성화할 수 있습니다.
    unnecessary_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
