name: dg_table
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.3
  flutter_svg: ^1.0.0
  syncfusion_flutter_calendar: ^22.1.34
  table_calendar: ^3.0.6
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_svg: ^1.0.0
  # syncfusion_flutter_calendar: ^22.1.34
  # table_calendar: ^3.0.6
  # intl: ^0.18.0


flutter:
  assets:
    - assets/fonts/HancomMalangMalang-Bold.ttf
    - assets/icon/nv_1.svg
    - assets/icon/nv_2.svg
    - assets/icon/nv_3.svg
    - assets/icon/nv_4.svg
    - assets/icon/nv_5.svg
    - assets/image/

  fonts:
    - family: MalangBold
      fonts:
        - asset: assets/fonts/HancomMalangMalang-Bold.ttf